import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import '../theme/light_theme.dart';
import 'screen/login_page.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Stitchanda',
      debugShowCheckedModeBanner: false,
      theme: lightTheme,
      home: const LoginPage(),
    );
  }
}